### PR TITLE
Upgrade | Use `saloonphp/saloon` instead of `Sammyjo20/Saloon`

### PR DESCRIPTION
**Pull request by Sammyjo20**
Hey! Awesome SDK - I recently just changed the organization that Saloon lives under to "saloonphp". I have updated this package accordingly.

### CODE REVIEW

**Comment by jo-argon7** [comment]
@guillaume-carbone could your please merge this PR ? this will prevent a warning when using your package. Tx!

**Comment by steevepay** [comment]
Done, thanks for the MR @Sammyjo20 !

**Comment by jo-argon7** [comment]
version tag to allow a smooth composer update? :)

**Comment by steevepay** [comment]
Done ;)

**Pull request merged**
